### PR TITLE
PIN-1300

### PR DESCRIPTION
**Pull request by nttdata-rtorsoli**
catalog-process POST /eservices/{eServiceId}/descriptors/{descriptorId}/documents

### CODE REVIEW

**Review by galales — COMMENTED** [review]
I think we may remove the file upload from this service, and let the BFF to directly do it, but let's discuss this on Monday

**Comment by beetlecrunch** [comment]
> I think we may remove the file upload from this service, and let the BFF to directly do it, but let's discuss this on Monday

File upload is done at the management level, so I totally agree with you about moving it to BFF.

**Comment by galales** [comment]
> File upload is done at the management level, so I totally agree with you about moving it to BFF.

@beetlecrunch Is the checksum verification (to avoid files duplication) still necessary?

**Comment by beetlecrunch** [comment]
> > File upload is done at the management level, so I totally agree with you about moving it to BFF.
> 
> @beetlecrunch Is the checksum verification (to avoid files duplication) still necessary?

Uniqueness is useful to protect us from excessive consumption of space and, more importantly, helps keep electronic services clean.
What do you think?

**Comment by galales** [comment]
> Uniqueness is useful to protect us from excessive consumption of space and, more importantly, helps keep electronic services clean. What do you think?

If I'm not wrong, this topic already rose but we did not come up with a solution.

In my opinion it's a nice complementary feature, but difficult to scale once attachments will be several tens of MB.
Thinking ahead, we still have a limit of 10MB on AWS API GW payload. I'm not sure if the solution to this limitation would allow us to pass the file to one of our services to calculate the checksum (for example if we leverage on S3 pre-signed urls).

If we find this feature worth it we can keep it, but we need also to find a solution to these issues.

**Comment by beetlecrunch** [comment]
> > Uniqueness is useful to protect us from excessive consumption of space and, more importantly, helps keep electronic services clean. What do you think?
> 
> If I'm not wrong, this topic already rose but we did not come up with a solution.
> 
> In my opinion it's a nice complementary feature, but difficult to scale once attachments will be several tens of MB. Thinking ahead, we still have a limit of 10MB on AWS API GW payload. I'm not sure if the solution to this limitation would allow us to pass the file to one of our services to calculate the checksum (for example if we leverage on S3 pre-signed urls).
> 
> If we find this feature worth it we can keep it, but we need also to find a solution to these issues.

I wasn't thinking about these side effects. Let's remove checksum control.

**Review by TonioGela — APPROVED** [review]

**Review by galales — APPROVED** [review]

**Review by beetlecrunch — APPROVED** [review]

**Pull request merged**
